[from-liveagent]
exten => u262625_876,1,NoOp(Inbound LiveAgent SIP trunk call to SIP user)
 same => n,Goto(voicebot-entry,s,1)

exten => _X!,1,NoOp(Inbound LiveAgent SIP trunk call to ${EXTEN})
 same => n,Goto(voicebot-entry,s,1)

exten => s,1,NoOp(Inbound LiveAgent SIP trunk call)
 same => n,Goto(voicebot-entry,s,1)

[voicebot-entry]
exten => s,1,Set(FLOWHUNT_CALL_ID=${UUID()})
 same => n,Answer()
 same => n,AudioSocket(${FLOWHUNT_CALL_ID},__AUDIOSOCKET_SERVICE__)
 same => n,Hangup()

[agent-transfer]
exten => _X!,1,NoOp(Transferring voicebot call to ${EXTEN})
 same => n,Transfer(PJSIP/${EXTEN}@liveagent-endpoint)
 same => n,Hangup()
