[from-liveagent]
exten => u262625_876,1,NoOp(Inbound LiveAgent SIP trunk call to SIP user)
 same => n,Answer()
 same => n,AudioSocket(40325ec2-5efd-4bd3-805f-53576e581d13,__AUDIOSOCKET_SERVICE__)
 same => n,Hangup()

exten => _X!,1,NoOp(Inbound LiveAgent SIP trunk call to ${EXTEN})
 same => n,Answer()
 same => n,AudioSocket(40325ec2-5efd-4bd3-805f-53576e581d13,__AUDIOSOCKET_SERVICE__)
 same => n,Hangup()

exten => s,1,NoOp(Inbound LiveAgent SIP trunk call)
 same => n,Answer()
 same => n,AudioSocket(40325ec2-5efd-4bd3-805f-53576e581d13,__AUDIOSOCKET_SERVICE__)
 same => n,Hangup()
